### ISSUE TITLE
Handle qtchooser

### ISSUE THREAD

**Issue by z3ntu** [ubports/cmake-extras#13]
Many distributions don't use qmlchooser (e.g. `qdoc -qt=qt5` or `qmlplugindump -qt=qt5`) but have `qdoc` or `qdoc-qt5` in their PATH.

Starting with Qt 5.14, Qt has a nice CMake module for qdoc: https://github.com/qt/qttools/blob/dev/src/qdoc/Qt5DocToolsConfig.cmake.in (but a solution is still needed for Qt 5.9+

content-hub and ubuntu-download-manager contain these `-qt=qt5` options and they currently have to be patched in source to compile on distros without qtchooser.

**Comment by UniversalSuperBox** [comment]
This issue report has been moved to https://gitlab.com/ubports/core/cmake-extras/-/issues/1
