### ISSUE TITLE
Cannot locate new Gmock

### ISSUE THREAD

**Issue by vanyasem** [ubports/cmake-extras#2]
I get this error while building on Arch GNU/Linux (amd64):
```
[7/32] Performing configure step for 'GMock'
FAILED: tests/GMock-prefix/src/GMock-stamp/GMock-configure 
cd /mnt/antihype/Projects/AUR/Unity8/_build/libqtdbustest-build/tests/gmock && /usr/bin/cmake "-DCMAKE_CXX_FLAGS= -g -Wno-old-style-cast -Wno-missing-field-initializers -Wno-ctor-dtor-privacy -Wno-switch-default" -GNinja /usr/src/gmock && /usr/bin/cmake -E touch /mnt/antihype/Projects/AUR/Unity8/_build/libqtdbustest-build/tests/GMock-prefix/src/GMock-stamp/GMock-configure
CMake Error: The source directory "/usr/src/gmock" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[15/32] Building CXX object src/libqtdbustest/CMakeFiles/qtdbustest.dir/DBusTestRunner.cpp.o
```
Gmock and Gtest are installed. Mir is able to detect their existence.

I assume that this commit in Mir https://github.com/MirServer/mir/commit/e7bbc0f2c7919acc770070ab2a9e27bd43eb8031 introduced support for it.

Same issue as https://github.com/ubports/ubuntu-download-manager/issues/2

**Comment by z3ntu** [comment]
For postmarketOS I've (also) patched in FindGtestGmock.cmake from mir into cmake-extras and it works fine.

**Comment by UniversalSuperBox** [comment]
This issue has been moved to https://gitlab.com/ubports/core/cmake-extras/-/issues/3. Please let me know if this is no longer relevant.
