### ISSUE TITLE
Should include QmlTest.cmake

### ISSUE THREAD

**Issue by z3ntu** [ubports/cmake-extras#6]
That file is currently included in the following packages:
* qtmir
* system-settings
* unity-api
* unity8
* settings-components

and it seems that each version is at least slightly different. It would be nice to make one version that's used in those packages.

**Comment by z3ntu** [comment]
`UseLttngGenTp.cmake` is also included in at least qtmir & ubuntu-app-launch

**Comment by UniversalSuperBox** [comment]
This report has been moved to https://gitlab.com/ubports/core/cmake-extras/-/issues/2
